"""table

Revision ID: 285a96eaef5e
Revises: 0786d6802744
Create Date: 2024-03-07 10:41:01.329103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285a96eaef5e'
down_revision = '0786d6802744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
