"""table

Revision ID: e13e1d42f577
Revises: 285a96eaef5e
Create Date: 2024-03-07 11:26:05.581944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13e1d42f577'
down_revision = '285a96eaef5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
