"""table

Revision ID: 62492d0d6d54
Revises: 9b0ba8626b80
Create Date: 2024-03-15 13:20:11.962170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62492d0d6d54'
down_revision = '9b0ba8626b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
